import { Command } from 'commander';
import { MikrotikClient } from '../client/MikrotikClient';
import { SchemaInferrer } from './SchemaInferrer';
import * as fs from 'fs-extra';
import * as path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import dotenv from 'dotenv';

// Load .env (if available)
dotenv.config();

const program = new Command();

program
    .name('ros-codegen')
    .description('Generates TypeScript interfaces from your live MikroTik router')
    .version('1.2.0')
    // Mandatory Generation Params
    .requiredOption('-p, --path <menu>', 'MikroTik Menu Path (e.g. /ppp/secret)')
    .requiredOption('-n, --name <interface>', 'Name of the output Interface (e.g. PPPSecret)')
    .option('-o, --output <dir>', 'Output directory', './src/generated')

    // Optional Connection Params (Overrides .env if provided)
    .option('--host <host>', 'Router Host/IP')
    .option('--user <user>', 'Router Username')
    .option('--pass <password>', 'Router Password')
    .option('--port <port>', 'Router API Port')
    .option('--tls', 'Use TLS (SSL) connection', false)

    .action(async (options) => {
        // ==========================================
        // 1. CREDENTIALS RESOLUTION STRATEGY
        // Priority: CLI Flag > Environment Variable
        // ==========================================

        const host = options.host || process.env.MIKROTIK_HOST;
        const user = options.user || process.env.MIKROTIK_USER;
        const password = options.pass || process.env.MIKROTIK_PASS;

        // TLS Logic: Flag OR Env Var string 'true'
        const useTLS = options.tls || process.env.MIKROTIK_USE_TLS === 'true';

        // Port Logic:
        // 1. CLI Flag
        // 2. Env Var
        // 3. Default based on TLS (8729 vs 8728)
        let port: number;
        if (options.port) {
            port = parseInt(options.port, 10);
        } else if (process.env.MIKROTIK_PORT) {
            port = parseInt(process.env.MIKROTIK_PORT, 10);
        } else {
            port = useTLS ? 8729 : 8728;
        }

        // Pre-flight Validation
        if (!host || !user || !password) {
            console.error(chalk.red('Error: Missing credentials.'));
            console.error(chalk.yellow('You must provide credentials via .env file OR CLI flags.'));
            console.log(chalk.gray(`
Usage Example:
  $ npm run codegen -- -p /ppp/secret -n ISecret --host 192.168.88.1 --user admin --pass admin
            `));
            process.exit(1);
        }

        const spinner = ora(`Connecting to ${host}:${port}...`).start();

        // Initialize Client
        const client = new MikrotikClient({
            host: host,
            user: user,
            password: password,
            port: port,
            useTLS: useTLS,
            allowInsecureConfig: true // Suppress warnings for CLI tool since hardcoding is expected here
        });

        try {
            await client.connect();

            spinner.text = `Fetching schema from ${options.path}...`;

            // Fetch Real Data (The "Truth")
            const data = await client.write(`${options.path}/print`);

            if (data.length === 0) {
                spinner.warn(chalk.yellow(' Warning: No data found in this menu. Generated interface will be empty or generic.'));
            }

            // Infer Schema
            spinner.text = 'Inferring Types & Generating Code...';
            const tsCode = SchemaInferrer.generateInterface(options.name, data);

            // Add File Header
            const fileContent = `
/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by rosinterface-cli v1.2.0
 * Source: ${options.path}
 * Date: ${new Date().toISOString()}
 */

${tsCode}
`;

            // Write to File
            const outputDir = path.resolve(options.output);
            await fs.ensureDir(outputDir);
            const filePath = path.join(outputDir, `${options.name}.ts`);

            await fs.writeFile(filePath, fileContent);

            spinner.succeed(chalk.green(`Successfully generated ${options.name}.ts in ${options.output}`));

            // Show Preview
            console.log(chalk.gray('\nPreview:'));
            console.log(chalk.cyan(tsCode.split('\n').slice(0, 15).join('\n') + '\n...'));

        } catch (error: any) {
            spinner.fail(chalk.red('Generation Failed'));

            if (error.code === 'ECONNREFUSED') {
                console.error(chalk.red(`Could not connect to ${host}:${port}. Check IP/Port.`));
            } else if (error.message && error.message.includes('login')) {
                console.error(chalk.red(`Authentication failed for user ${user}. Check password.`));
            } else {
                console.error(chalk.red(error.message));
            }
        } finally {
            client.close();
            process.exit(0);
        }
    });

program.parse(process.argv);